name: [不使用，仅做备份]强制同步到主仓库

on:
  schedule:
    # 北京时间每8小时运行一次：04:00 (UTC 20:00)，12:00 (UTC 04:00)，20:00 (UTC 12:00)
    #- cron: '0 4,12,20 * * *'
  # workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送更改

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Add topstream remote
        run: |
          git remote add topstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
          git fetch topstream

      - name: Try to merge changes
        id: merge
        run: |
          # 配置 Git 用户
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          
          # 尝试合并（忽略不相关历史）
          if git merge topstream/master --allow-unrelated-histories -m "Merge topstream updates"; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            # 检测是否为真实冲突（非空提交）
            if [ -n "$(git status --porcelain)" ]; then
              echo "::error::Merge conflict detected!"
              exit 1
            else
              echo "status=no-changes" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Push changes
        if: steps.merge.outputs.status == 'success'
        run: git push origin ${{ github.ref }}

      - name: Create issue on conflict
        if: ${{ failure() && steps.merge.conclusion == 'failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "⚠️ Merge conflict with topstream",
              body: `自动合并失败！需要手动解决冲突：\n\n` +
                    `工作流运行: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            })
